<?php

namespace AppBundle\Repository;

/**
 * EventContributorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventContributorRepository extends \Doctrine\ORM\EntityRepository
{
}
