<?php

namespace AppBundle\Repository;

/**
 * EventContributorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventContributorRepository extends \Doctrine\ORM\EntityRepository
{
    public function deleteContributor($id)
    {
        $qb = $this->createQueryBuilder();
        $qb->delete('AppBundle:EventContributor', 'ec')
        ->where('ec.id = :id')
        ->setParameter('id', $id);
        //DELETE FROM `nec_nn_eve_con` WHERE `nec_nn_eve_con` . `nec_oid` = 5
    }
}
