<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * RoomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomRepository extends \Doctrine\ORM\EntityRepository
{

public function findAllRoom($id)
{

  return $this->getEntityManager() 
    ->createQuery( 'SELECT r.Name, r.id 
    FROM AppBundle:Room r 
    INNER JOIN AppBundle:Event e 
    WITH r.id = e.rooOid 
    INNER JOIN AppBundle:Workshop w 
    WITH e.worOid = w.id 
    WHERE w.usrOid = :id' ) 
    ->setParameter('id', $id) 
    ->getResult(); 
}
}
